spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhixingyizhan?useSSL=false&serverTimezone=UTC
    username: alight
    password: "@twq9512368748"
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: none
server:
  port: 8089